project:
  type: website

website:
  title: "GEO511_FinalProject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex  # choose your theme here: https://bootswatch.com/
    toc: true
    highlight: textmate
    toc_depth: 2
    includes:
      after_body: include/after_body.html
    keep_md: false
