on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
  pages: write

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/geospatial:latest
    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          #Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "install.packages(c('testthat','RCurl','questionr'))"
          Rscript -e "questionr::qscan(list.files(pattern='*.R',recursive=T), load = TRUE, detail = FALSE)"
      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
